name: Build Flutter APK's and App bundle

# Controls when the workflow will run
on: 
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./frontend  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter doctor -v

      # setup go
      - name: Golang Action
        uses: actions/setup-go@v5.0.0 

      # Checkout the repository code and get packages.
      - name: Checkout flutter_app code
        uses: actions/checkout@v3
      - run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --release --no-tree-shake-icons

      - name: Build APP BUNDLE
        run: flutter build appbundle

      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "frontend/build/app/outputs/flutter-apk/*.apk, frontend/build/app/outputs/bundle/release/*.aab"
         
      
      - name: Checkout code
        uses: actions/checkout@v2
      - run: cd backend/cmd/api
      - run: GOOS=linux GOARCH=amd64 go build -o server-linux-amd64 .
      - run: mv server-linux-amd64 ../../../frontend/build/app/outputs/flutter-apk/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: release-apk
          path: frontend/build/app/outputs/flutter-apk/
